/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Wed May 31 22:57:29 CST 2017
 * 
 */
#ifndef __vpi_wrapper_matchtable_write_send_frame_h__
#define __vpi_wrapper_matchtable_write_send_frame_h__

#include <vpi_user.h>

/* registration function */
void matchtable_write_send_frame_vpi_register();

/* VPI wrapper function */
PLI_INT32 matchtable_write_send_frame_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_matchtable_write_send_frame_h__ */
