/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Wed May 31 23:49:44 CST 2017
 * 
 */
#ifndef __vpi_wrapper_mem_create_h__
#define __vpi_wrapper_mem_create_h__

#include <vpi_user.h>

/* registration function */
void mem_create_vpi_register();

/* VPI wrapper function */
PLI_INT32 mem_create_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_mem_create_h__ */
