
set partname {xc7z020clg484-1}
set boardname {bluesim}
## for compatibility with older fpgamake. will be removed.
set xbsvipdir {/home/netarchlab/p4fpga/connectal/out}
set ipdir {/home/netarchlab/p4fpga/connectal/out}
set connectaldir {/home/netarchlab/p4fpga/connectal}
set need_pcie {unused}
set connectal_dut {mkXsimTop}
set PARSER {Parser}
set DEPARSER {Deparser}
set MATCHTABLE {Control}
set TYPEDEF {StructDefines}
set NUM_RXCHAN {1}
set NUM_TXCHAN {1}
set NUM_HOSTCHAN {1}
set STREAM {}
set NicVersion {2778269842}
set DataBusWidth {128}
set IMPORT_HOSTIF {}
set BYTE_ENABLES {}
set ClockDefaultParam {}
set ConnectalVersion {17.01.2}
set NumberOfMasters {1}
set PinType {Empty}
set PinTypeInclude {Misc}
set NumberOfUserTiles {1}
set SlaveDataBusWidth {32}
set SlaveControlAddrWidth {5}
set BurstLenSize {12}
set project_dir {$(DTOP)}
set MainClockPeriod {20}
set DerivedClockPeriod {10.000000}
set CnocTop {}
set XsimHostInterface {}
set PhysAddrWidth {40}
set SIMULATION {}
set CONNECTAL_BITS_DEPENDENCES {bsim}
set BOARD_bluesim {}
